language: python

sudo: false

python:
  - "3.5"

services:
  - mysql

cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.cache/venvs"

env:
  - DJANGO_SETTINGS_MODULE="ipv6map.settings.test" DB_USER="travis"

install:
  - pip install -U pip
  - pip install -U -r requirements.txt

before_script:
  - mysql -e "CREATE DATABASE ipv6map CHARACTER SET UTF8;"

script:
  - pipconflictchecker
  - python manage.py makemigrations --dry-run --check
  - coverage run manage.py test
  - coverage report
  - flake8 .
